/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in': 'fadeIn 0.3s ease-in both',
        'fade-in-up': 'fadeInUp 0.5s ease-out both',
        'fade-in-down': 'fadeInDown 0.5s ease-out both',
        'fade-in-left': 'fadeInLeft 0.5s ease-out both',
        'fade-in-right': 'fadeInRight 0.5s ease-out both',
        'slide-in-up': 'slideInUp 0.6s ease-out both',
        'slide-in-down': 'slideInDown 0.6s ease-out both',
        'slide-in-left': 'slideInLeft 0.6s ease-out both',
        'slide-in-right': 'slideInRight 0.6s ease-out both',
        'scale-in': 'scaleIn 0.4s ease-out both',
        'scale-out': 'scaleOut 0.4s ease-in both',
        'bounce-in': 'bounceIn 0.8s ease-out both',
        'bounce-in-up': 'bounceInUp 0.8s ease-out both',
        'bounce-in-down': 'bounceInDown 0.8s ease-out both',
        'rotate-in': 'rotateIn 0.6s ease-out both',
        'flip-in': 'flipIn 0.8s ease-out both',
        'zoom-in': 'zoomIn 0.4s ease-out both',
        'zoom-out': 'zoomOut 0.4s ease-in both',
        'shimmer': 'shimmer 2s linear infinite',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
        'float': 'float 3s ease-in-out infinite',
        'wiggle': 'wiggle 0.5s ease-in-out infinite',
        'shake': 'shake 0.5s ease-in-out infinite',
        'heartbeat': 'heartbeat 1.5s ease-in-out infinite',
        'typing': 'typing 2s steps(40, end) infinite',
        'blink': 'blink 1s infinite',
        'gradient': 'gradient 3s ease infinite',
        'morph': 'morph 4s ease-in-out infinite',
        'wave': 'wave 2s ease-in-out infinite',
        'spin-slow': 'spin 3s linear infinite',
        'ping-slow': 'ping 3s cubic-bezier(0, 0, 0.2, 1) infinite',
        'bounce-slow': 'bounce 2s infinite',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        display: ['var(--font-poppins)', 'Poppins', 'system-ui', 'sans-serif'],
        mono: ['var(--font-roboto-mono)', 'Roboto Mono', 'monospace'],
        body: ['var(--font-open-sans)', 'Open Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
      },
      fontWeight: {
        'light': '300',
        'normal': '400',
        'medium': '500',
        'semibold': '600',
        'bold': '700',
      },
    },
    keyframes: {
      fadeIn: {
        '0%': { opacity: '0' },
        '100%': { opacity: '1' },
      },
      fadeInUp: {
        '0%': { opacity: '0', transform: 'translateY(30px)' },
        '100%': { opacity: '1', transform: 'translateY(0)' },
      },
      fadeInDown: {
        '0%': { opacity: '0', transform: 'translateY(-30px)' },
        '100%': { opacity: '1', transform: 'translateY(0)' },
      },
      fadeInLeft: {
        '0%': { opacity: '0', transform: 'translateX(-30px)' },
        '100%': { opacity: '1', transform: 'translateX(0)' },
      },
      fadeInRight: {
        '0%': { opacity: '0', transform: 'translateX(30px)' },
        '100%': { opacity: '1', transform: 'translateX(0)' },
      },
      slideInUp: {
        '0%': { transform: 'translateY(100%)' },
        '100%': { transform: 'translateY(0)' },
      },
      slideInDown: {
        '0%': { transform: 'translateY(-100%)' },
        '100%': { transform: 'translateY(0)' },
      },
      slideInLeft: {
        '0%': { transform: 'translateX(-100%)' },
        '100%': { transform: 'translateX(0)' },
      },
      slideInRight: {
        '0%': { transform: 'translateX(100%)' },
        '100%': { transform: 'translateX(0)' },
      },
      scaleIn: {
        '0%': { transform: 'scale(0.8)', opacity: '0' },
        '100%': { transform: 'scale(1)', opacity: '1' },
      },
      scaleOut: {
        '0%': { transform: 'scale(1)', opacity: '1' },
        '100%': { transform: 'scale(0.8)', opacity: '0' },
      },
      bounceIn: {
        '0%': { transform: 'scale(0.3)', opacity: '0' },
        '50%': { transform: 'scale(1.05)' },
        '70%': { transform: 'scale(0.9)' },
        '100%': { transform: 'scale(1)', opacity: '1' },
      },
      bounceInUp: {
        '0%': { transform: 'translateY(100%)', opacity: '0' },
        '60%': { transform: 'translateY(-10px)', opacity: '1' },
        '100%': { transform: 'translateY(0)' },
      },
      bounceInDown: {
        '0%': { transform: 'translateY(-100%)', opacity: '0' },
        '60%': { transform: 'translateY(10px)', opacity: '1' },
        '100%': { transform: 'translateY(0)' },
      },
      rotateIn: {
        '0%': { transform: 'rotate(-200deg)', opacity: '0' },
        '100%': { transform: 'rotate(0)', opacity: '1' },
      },
      flipIn: {
        '0%': { transform: 'perspective(400px) rotateY(90deg)', opacity: '0' },
        '40%': { transform: 'perspective(400px) rotateY(-20deg)' },
        '60%': { transform: 'perspective(400px) rotateY(10deg)' },
        '80%': { transform: 'perspective(400px) rotateY(-5deg)' },
        '100%': { transform: 'perspective(400px) rotateY(0deg)', opacity: '1' },
      },
      zoomIn: {
        '0%': { transform: 'scale(0.5)', opacity: '0' },
        '100%': { transform: 'scale(1)', opacity: '1' },
      },
      zoomOut: {
        '0%': { transform: 'scale(1)', opacity: '1' },
        '100%': { transform: 'scale(0.5)', opacity: '0' },
      },
      shimmer: {
        '0%': { backgroundPosition: '-200% 0' },
        '100%': { backgroundPosition: '200% 0' },
      },
      pulseGlow: {
        '0%, 100%': { boxShadow: '0 0 5px rgba(59, 130, 246, 0.5)' },
        '50%': { boxShadow: '0 0 20px rgba(59, 130, 246, 0.8)' },
      },
      float: {
        '0%, 100%': { transform: 'translateY(0px)' },
        '50%': { transform: 'translateY(-10px)' },
      },
      wiggle: {
        '0%, 100%': { transform: 'rotate(-3deg)' },
        '50%': { transform: 'rotate(3deg)' },
      },
      shake: {
        '0%, 100%': { transform: 'translateX(0)' },
        '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-5px)' },
        '20%, 40%, 60%, 80%': { transform: 'translateX(5px)' },
      },
      heartbeat: {
        '0%': { transform: 'scale(1)' },
        '14%': { transform: 'scale(1.1)' },
        '28%': { transform: 'scale(1)' },
        '42%': { transform: 'scale(1.1)' },
        '70%': { transform: 'scale(1)' },
      },
      typing: {
        '0%': { width: '0' },
        '50%': { width: '100%' },
        '100%': { width: '0' },
      },
      blink: {
        '0%, 50%': { opacity: '1' },
        '51%, 100%': { opacity: '0' },
      },
      gradient: {
        '0%, 100%': { backgroundPosition: '0% 50%' },
        '50%': { backgroundPosition: '100% 50%' },
      },
      morph: {
        '0%, 100%': { borderRadius: '60% 40% 30% 70% / 60% 30% 70% 40%' },
        '50%': { borderRadius: '30% 60% 70% 40% / 50% 60% 30% 60%' },
      },
      wave: {
        '0%': { transform: 'rotate(0deg)' },
        '10%': { transform: 'rotate(14deg)' },
        '20%': { transform: 'rotate(-8deg)' },
        '30%': { transform: 'rotate(14deg)' },
        '40%': { transform: 'rotate(-4deg)' },
        '50%': { transform: 'rotate(10deg)' },
        '60%': { transform: 'rotate(0deg)' },
        '100%': { transform: 'rotate(0deg)' },
      },
    },
  },
  plugins: [],
} 